---
- name: Installing ucp 3.0.0
  command: docker container run --rm -it --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:3.0.0 install --host-address 192.168.1.13 --admin-username admin --admin-password admin123 --san ucp.example.com --force-minimums