---
  #Playbook que rodará na criação da máquina virtual vagrant
- hosts: dk1
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: no

  vars_files:
    ./roles/default/main.yml

  roles:
  - packages
  - user
  - swarm
  - ucp

  handlers:
  - include: roles/handlers/tasks/main.yml
